# Spatial Analysis of Fatal Automobile Accidents

### Using Density-based Clustering for Pattern Detection in Fatal Car Accident Data

You may not be surprised to learn that transportation in the United States is dominated by automobiles. Of all the miles traveled by American passengers in 2016, 86% occurred in cars (BTS 2017). 

But did you know that fatal automobile accidents are a growing problem?

In just 2016, there were 34,439 reported fatal crashes, an increase of 12% since 2014! The rise in fatal accidents cannot be simply attributed to more vehicles on roads; fatality rates per miles traveled have also increased: 2016 rates are nine percent higher than in 2014. It’s an unfortunate statistic, but before the day ends, more than 100 people will have likely lost their lives in the nation’s roads (NHTSA, Fatality Analysis Reporting System 2017).

#### How Can We Help Address the Problem?

Addressing this problem is an important but monumental task. There are millions of car accidents each year and limited available resources for the design and implementation of safety measures across the nation. 

For this reason, finding and prioritizing locations where systemic issues result in multiple fatal car accidents is a crucial need for transportation agencies that run operations and guide safety policy. A spatial approach can help us expand beyond our basic understanding of where fatal car accidents occur and start detecting patterns that find these needles in the haystack. 

To do this, we'll start with the Language of Spatial Analysis, consisting of a core set of questions we ask, a taxonomy that organizes and expands our understanding, and the fundamental steps to spatial analysis that embody how we solve spatial problems.

## Language of Spatial Analysis: Exploring the Problem and Data

The six categories (and 26 questions) of spatial analysis:

#####  Understanding where

1. Understanding where things are (location maps)
2. Understanding where the variations and patterns in values are (comparative maps)
3. Understanding where and when things change

#####  Measuring size, shape, and distribution

4. Calculating individual feature geometries
5. Calculating geometries and distributions of feature collections

#####  Determining how places are related

6. Determining what is nearby or coincident
7. Determining and summarizing what is within an area(s)
8. Determining what is closest
9. Determining what is visible from a given location(s)
10. Determining overlapping relationships in space and time

#####  Finding the best locations and paths

11. Finding the best locations that satisfy a set of criteria
12. Finding the best allocation of resources to geographic areas
13. Finding the best route, path, or flow along a network
14. Finding the best route, path, or corridor across open terrain
15. Finding the best supply locations given known demand and a travel network

#####  Detecting and quantifying patterns

16. Where are the significant hot spots, anomalies, and outliers?
17. What are the local, regional, and global spatial trends?
18. Which features/pixels are similar, and how can they be grouped together?
19. Are spatial patterns changing over time?

#####  Making predictions

20. Given a success case, identifying, ranking, and predicting similar locations
21. Finding the factors that explain observed spatial patterns and making predictions
22. Interpolating a continuous surface and trends from discrete sample observations
23. Predicting how and where objects spatially interact (attraction and decay)
24. Predicting how and where objects affect wave propagation
25. Predicting where phenomena will move, flow, or spread
26. Predicting what-if

## Language of Spatial Analysis Applied to Fatal Car Accidents Problems

In this section, we will find which aspects of the Language of Spatial Analysis which are applicable when attempting to understand the characteristics of fatal car accidents and the reasons why they are increasing throughout the country. 

The underlying goal as we address each question is the following: NHTSA would like to have a repeatable process to identify the locations that have become a more significant problem and have most greatly contributed to the increase of fatal car accidents across the nation, with consideration for population and vehicle miles traveled (VMT) growth. The knowledge of these locations can help them produce reports that can mobilize the right groups to action in the efforts to implement safety measures and save lives.

#####  Understanding where

1. Understanding where things are (location maps)
    - **_Where are fatal car accidents in the United States located?_**
        - FARS point locations
    - Where are fatal car accidents in the US by type of accident?
        - FARS symbolized by type of crash

2. Understanding where the variations and patterns in values are (comparative maps) 
    - Where are the highest levels of fatal crashes per state?
        - Thematic map of fatal crashes by state
    - **_Which states have the highest levels of fatal crashes per capita?_**
        - Thematic map of fatal crashes per capita
    - Where are the greatest concentrations of fatal crashes in the country?
        - Heat map of fatal car accidents
    
3. Understanding where and when things change
    - Where are current accidents happening? (Deferred)
        - Operations Dashboard connected to Waze data

#####  Measuring size, shape, and distribution

4. Calculating individual feature geometries
    
    - What is the sinuosity of the road centerline where a crash occurred?
        - Map of crashes by road sinuosity

5. Calculating geometries and distributions of feature collections
    - N/A 
        
#####  Determining how places are related

6. Determining what is nearby or coincident
    - Which roads can be associated with each cluster of fatal car crashes?

7. Determining and summarizing what is within an area(s)
    - How many fatal crashes can we find in each state?
        - Thematic map of fatal crashes by state
    - Which states have the highest levels of fatal crashes per capita?
        - Thematic map of fatal crashes per capita

8. Determining what is closest
    - What is the cloasest road segment to each crash?
    - **_What is the cloasest road segment to each crash cluster?_**

9. Determining what is visible from a given location(s)
    - For crash clusters at a 4-way intersection, how many stop signs have poor visibility? (Deferred)

10. Determining overlapping relationships in space and time
    - When will snow weather events overlap with road segments that have a significant fatal crash cluster? 

#####  Finding the best locations and paths

11. Finding the best locations that satisfy a set of criteria
12. Finding the best allocation of resources to geographic areas
    - Given all crashes in Maryland, where can we place boundaries to organize the investigation of groups of related crashes?
        - DBSCAN clustering of Maryland Crash Data

13. Finding the best route, path, or flow along a network
    - Given a risk adverse transportation need, and given an assignment of relative risk to each road segment as an impedance factor, what is the best route to minimize fatal car accident risk?


14. Finding the best route, path, or corridor across open terrain
15. Finding the best supply locations given known demand and a travel network

#####  Detecting and quantifying patterns

16. Where are the significant hot spots, anomalies, and outliers?
    - **_Where are the spatial clusters of fatal car accidents where more than incidents occurred within 300 meters of the same road segment?_**
        - DBSCAN outputs of FARS
    
    - Where are the statistically significant clusters of high fatal car crashes?
        - Getis-Ord Gi Hot Spots with buffered roads as a masked possibility space
        
17. What are the local, regional, and global spatial trends?
    - How does the clustering of fatal car crashes concentrations vary at increasing scales from a county, to a state, to the country?
        - Incremental Spatial Autocorrelation of FARS
       

18. Which features/pixels are similar, and how can they be grouped together?
    - What are the clusters with similar characteristics based on crash attributes (time of day, type of crash) and road elements (intersections, pedestrian crossing, high speed limits, curvy road) 
        - Grouping analysis of Fatal Car Accidents based on crash details and road attributes


19. Are spatial patterns changing over time?
    - **_Are fatal car crashes becoming more or less clustered over time?_** 
        - Emerging Hot Spots of multiple years of FARS data
        
    - **_Are crashes of a specific type showing a more pronounced increase trend over time?_**
        - Emerging Hot Spots of FARS crashes grouped by crash type (i.e. pedestrian fatality | high-speed fatality)

#####  Making predictions

20. Given a success case, identifying, ranking, and predicting similar locations
    - Given a location where a safety measure was implemented that resulted in a statistically significant decrease in fatal car crashes, where are other similar locations?
        - Find a location that dimished as a hot spot in the EHS analysis, determine if a safety measure was put in place, and run similarity search to identify candidate locations that could benefit from the same help.

21. Finding the factors that explain observed spatial patterns and making predictions
    - Which factors are most directly related to the propensity of a fatal car crash in a road segment? 
        - Exploratory regression of road segments with known fatal crashes
        - Deep Learning model to find factors that result in a fatal crash

22. Interpolating a continuous surface and trends from discrete sample observations
    - What is the fatal car accident risk level across a road network? 
        - Impedance factor for fatal car accient risk level.

23. Predicting how and where objects spatially interact (attraction and decay)


24. Predicting how and where objects affect wave propagation


25. Predicting where phenomena will move, flow, or spread


26. Predicting what-if
    - What if we lower speed limits at road segments with a specified sinuosity? 
    - What if we change a four-way stop intersection into a traffic light or roundabout? 
    - What if a problematic weather event intersects a high risk road... should we close the road to prevent fatal car accidents? What would be the threshold?

## The seven steps to successful spatial analysis

### 1. Ask questions: Formulate hypotheses and spatial questions.

##### Candidates

    - Spatial Question: **_Where are fatal car accidents in the United States located?_**
    - Hypothesis: Fatal Car Accidents in the United States will be mostly located in areas with high populations.
    - Utility: We need to answer the basic questions regarding the location of our data. Knowing where each crash is can lead us to answering more complex questions. 
    - Result: 
    
    
    - Spatial Question: Which states/counties have the highest levels of fatal crashes per capita?
    - Hypothesis: Fatal Car Accidents in the United States will be mostly located in areas with high populations. 
    - Utility: Counties with higher fatal car accidents per capita are a more severe problem. This information can help prioritize safety measures and addressing of the problem.
    - Result: 
    
    
    - Spatial Question: **_Where are the spatial clusters of fatal car accidents where more than incidents occurred within 300 meters of the same road segment?_**
    - Utility: Finding these locations identifies where a possible safety problem has resulted in multiple incidents with a fatality on the road. These locations are likely the best candidates for immediate remediation.
    - Hypothesis: N/A - I am not really certain where these spatial clusters will be. 
    - Methodology: Density-based Clustering with specified distance.
    - Result: 
    
    
    - Spatial Question: **_What are the clusters with similar characteristics based on crash attributes (time of day, type of crash) and road elements (intersections, pedestrian crossing, high speed limits, curvy road)_**
    - Utility: Locations where the same type of incident happened multiple types on the same road segment are likely very good candidate opportunities to immediately help save lives with safety measures. 
    - Hypothesis: N/A - I am not really certain where these spatial clusters will be. 
    - Methodology: 
        - Grouping analysis of Fatal Car Accidents based on crash details and road attributes
    - Result:     


    - Spatial Question: **_What is the closest road segment to each crash cluster?_**
    - Utility: If we know which road segments can be attributed to a cluster of fatal crashes, we can consider the characteristics of the road segment for understanding the problem and prioritizing solutions. 
    - Hypothesis: Clusters will mostly be found in highway interchanges with highly curved roads. 
    - Result: 


    - Spatial Question: **_Are fatal car crashes becoming more or less clustered over time?_**
    - Utility: Locations where fatal car accidents are becoming a worse problem will receive priority in our recommendations for safety measure implementation.
    - Hypothesis: N/A. 
    - Methodology: 
        - Emerging Hot Spots of FARS crashes
        - Locations that are statistically significant are used when evaluating crash types. If location has increasing trend, the priority score includes this as a factor to increase priority. If location has decreasing trend, the priority score decreases accordingly. 
    - Result: 
        
        
    - Spatial Question: **_Are crashes of a specific type showing a more pronounced increase trend over time?_**
    - Utility: The factors that lead to a fatal crash are likely very different for each crash type. For instance, a pedestrian fatality is likely caused by very different factors than a high-speed interstate highway fatality. Understanding the trends for each type of fatal crash can help us find areas where a specific type of problem is becoming worse. This can help increase or decrease the priority score of each cluster if the temporal trend is significant. 
    - Hypothesis:
    - Methodology:
        - Emerging Hot Spots of FARS crashes grouped by crash type (i.e. pedestrian fatality | high-speed fatality)
        - Locations that are statistically significant are used when evaluating crash types. If location has increasing trend, the priority score includes this as a factor to increase priority. If location has decreasing trend, the priority score decreases accordingly. 
        - These factors are weighed higher than the broad temporal trend factor from the previous question. For instance, if the cluster being prioritized has a designation of "pedestrian-heavy problem" and the trend for pedestrian trends is increasing, then a boost to the priority should be added. 
    - Result:

##### Selected Questions
    
    - Spatial Question: **_Where are fatal car accidents in the United States located?_**
    - Hypothesis: Fatal Car Accidents in the United States will be mostly located in areas with high populations.
    - Utility: We need to answer the basic questions regarding the location of our data. Knowing where each crash is can lead us to answering more complex questions. 
    - Result: 
    
    
    - Spatial Question: **_Where are the spatial clusters of fatal car accidents where more than three incidents occurred within 300 meters of the same road segment?_**
    - Utility: Finding these locations identifies where a possible safety problem has resulted in multiple incidents with a fatality on the road. These locations are likely the best candidates for immediate remediation.
    - Hypothesis: N/A - I am not really certain where these spatial clusters will be. 
    - Methodology: Density-based Clustering with specified distance.
    - Result: 
    
    
    - Spatial Question: **_What are the clusters with similar characteristics based on crash attributes (time of day, type of crash) and road elements (intersections, pedestrian crossing, high speed limits, curvy road)_**
    - Utility: Locations where the same type of incident happened multiple types on the same road segment are likely very good candidate opportunities to immediately help save lives with safety measures. 
    - Hypothesis: N/A - I am not really certain where these spatial clusters will be. 
    - Methodology: 
        - Grouping analysis of Fatal Car Accidents based on crash details and road attributes
    - Result:

### 2. Explore the data: Examine the data quality, completeness, and measurement limitations (scale and resolution) to determine the level of analysis and interpretation that can be supported.

This section contains logic to retrieve NHTSA's FARS data from their FTP servers and convert to GIS formats that we can explore and evaluate. The process is current as of December, 2017.

In [2]:
import pandas as pd
import arcgis
import zipfile
import os
import arcpy
import urllib
import getpass
import numpy as np

In [3]:
portals_dict = {
    "esrifederal_gis": r"https://esrifederal.maps.arcgis.com",
    "natgov_gis": r"http://esri-natgov105.eastus.cloudapp.azure.com/arcgis",
    "dot_gis": r"http://dot.esri.com/portal",
    "dev_gis": r"http://govdev.eastus.cloudapp.azure.com/arcgis",
    "local_gis": r"https://anieto.esri.com/arcgis",
    "science_agol_org": r"https://science.maps.arcgis.com"
}

In [4]:
gis_url = portals_dict["natgov_gis"]

In [5]:
if gis_url == portals_dict["esrifederal_gis"]:
#     gis_app_id = getpass.getpass(prompt="App ID: ")
    gis_app_id = r"wt3QUR1M4eum0TVI"
    print("Attempting to log in to '{0}'...".format(gis_url))
    gis = arcgis.gis.GIS(gis_url, client_id=gis_app_id)
    print("Successfully logged in as: " + gis.properties.user.username)
else:
    gis_username = getpass.getpass(prompt="Username: ")
    gis_pw = getpass.getpass(prompt="Password: ")
    print("Attempting to log in to '{0}'...".format(gis_url))
    gis = arcgis.gis.GIS(gis_url, gis_username, gis_pw, verify_cert=False)
    print("Successfully logged in as: " + gis.properties.user.username)

Username: ········
Password: ········
Attempting to log in to 'http://esri-natgov105.eastus.cloudapp.azure.com/arcgis'...
Successfully logged in as: anieto

In [6]:
arcpy.env.overwriteOutput = True

NameError: name 'arcpy' is not defined

In [6]:
# # Helper function to download the FARS data for any given year
# from ftplib import FTP
# def download_raw_fars_for_single_year(year, workspace):
#     # Set reference to the FARS URL location
#     fars_ftp_url = r"ftp://ftp.nhtsa.dot.gov/fars"
#     # establish url for year
#     fars_year_url = "{0}/{1}/National/FARS{1}NationalCSV.zip".format(fars_ftp_url, year)
#     print("Downloading data from '{0}'...".format(fars_year_url))
#     # Download and unzip the zipped fars dataset
#     target_file = "{0}\\{1}".format(workspace, "FARS{0}NationalCSV.zip")
    
#     ftp = FTP(fars_year_url)
#     ftp.retrbinary("RETR " + file ,open(target_file, 'wb').write)
#     ftp.close()

#     print("Unzipping in '{0}' directory...".format(workspace))
#     zipDocument = zipfile.ZipFile(io.BytesIO(target_file))
#     zipDocument.extractall(path=workspace)
#     unzipped_dir = "{0}\\{1}".format(workspace, "FARS{0}NationalCSV")
#     accidents_csv = "{0}\\accident.csv"
#     print("Downloaded and unzipped to '{0}'!".format(unzipped_dir))
#     return accidents_csv

In [7]:
# # Set reference to a list of years we will work with
# data_years = [2016, 2015, 2014]

# workspace = r"C:\Users\albe9057\Documents\GitHub\FatalCarAccidents_SpatialAnalysis\inputs"

# # For each year in data_years, retrieve the csv of FARS data
# for data_year in data_years:
#     download_raw_fars_for_single_year(data_year, workspace)

In [8]:
# Set static reference to downloaded files (for now)
fars_2015_csv = r"D:\ANieto_SolutionEngineer\Data\DOT\NHTSA\FARS2015NationalCSV\accident.csv"
fars_2016_csv = r"D:\ANieto_SolutionEngineer\Data\DOT\NHTSA\FARS2016NationalCSV\accident.csv"
workspace = r"C:\Users\albe9057\Documents\GitHub\FatalCarAccidents_SpatialAnalysis\inputs"

In [9]:
def concat_two_csvs(csv_one,
                    csv_two,
                    output_dir,
                    output_name,
                    check_for_unnamed_fields=False):
    """
    Concatenates two csvs
    :param csv_one:
    :param csv_two:
    :param output_dir:
    :param output_name:
    :param check_for_unnamed_fields:
    :return: Output concatenated csv
    """
    import pandas as pd
    import os.path

    method_message = "\t\t\tconcat_two_csvs: "

    print("{0}Concatenating csvs...".format(method_message),
          "INFO")
    a = pd.read_csv(csv_one, index_col=None, header=0)
    b = pd.read_csv(csv_two, index_col=None, header=0)
    list_ = [a, b]
    df = pd.concat(list_)
    print("{0}Checking for unnamed fields...".format(method_message),
          "INFO")
    if check_for_unnamed_fields:
        if "Unnamed: 0" in df.columns:
            print('{0}"Unnamed: 0" field found. Removing...'.format(method_message),
                  "INFO")
            df.drop("Unnamed: 0", axis=1, inplace=True)
        else:
            print('{0}"No unnamed fields found.'.format(method_message),
                  "INFO")
    output_csv = "{0}\\{1}".format(output_dir, output_name)
    if os.path.isfile(output_csv):
        print("{0}Pre-existing output csv found. Removing...".format(method_message),
              "INFO")
        os.remove(output_csv)
    df.to_csv(output_csv)
    return df, output_csv

In [10]:
fars_df, fars_csv = concat_two_csvs(fars_2015_csv, fars_2016_csv, r"D:\ANieto_SolutionEngineer\Data\DOT\NHTSA", "fars_2015_2016.csv")
fars_df

			concat_two_csvs: Concatenating csvs... INFO
			concat_two_csvs: Checking for unnamed fields... INFO
			concat_two_csvs: Pre-existing output csv found. Removing... INFO

,STATE,ST_CASE,VE_TOTAL,VE_FORMS,PVH_INVL,PEDS,PERNOTMVIT,PERMVIT,PERSONS,COUNTY,...,NOT_MIN,ARR_HOUR,ARR_MIN,HOSP_HR,HOSP_MN,CF1,CF2,CF3,FATALS,DRUNK_DR
0,1,10001,1,1,0,0,0,1,1,127,...,99,2,58,88,88,0,0,0,1,1
1,1,10002,1,1,0,0,0,1,1,83,...,99,22,20,88,88,0,0,0,1,0
2,1,10003,1,1,0,0,0,2,2,11,...,99,1,45,99,99,0,0,0,1,1
3,1,10004,1,1,0,0,0,1,1,45,...,99,1,15,88,88,0,0,0,1,1
4,1,10005,2,2,0,0,0,2,2,45,...,99,7,16,88,88,0,0,0,1,0
5,1,10006,1,1,0,0,0,2,2,111,...,99,10,17,99,99,0,0,0,1,0
6,1,10007,1,1,0,0,0,2,2,89,...,99,18,38,99,99,0,0,0,1,0
7,1,10008,1,1,0,1,1,1,1,73,...,99,21,48,99,99,0,0,0,1,0
8,1,10009,1,1,0,0,0,1,1,117,...,99,8,3,88,88,0,0,0,1,0
9,1,10010,2,2,0,0,0,2,2,33,...,99,19,1,99,99,0,0,0,1,0
10,1,10011,2,2,0,0,0,2,2,83,...,99,21,20,88,88,0,0,0,1,0
11,1,10012,3,3,0,0,0,6,6,95,...,99,6,41,99,99,0,0,0,1,0
12,1,10013,1,1,0,0,0,1,1,87,...,88,88,88,88,88,0,0,0,1,1
13,1,10014,1,1,0,0,0,1,1,11,...,99,6,29,88,88,0,0,0,1,1
14,1,10015,1,1,0,0,0,1,1,127,...,99,8,55,88,88,0,0,0,1,0
15,1,10016,2,2,0,0,0,2,2,81,...,99,17,30,99,99,0,0,0,1,0
16,1,10017,1,1,0,0,0,1,1,97,...,99,14,50,99,99,0,0,0,1,0
17,1,10018,1,1,0,0,0,2,2,1,...,99,19,35,99,99,0,0,0,1,1
18,1,10019,1,1,0,0,0,1,1,121,...,88,88,88,88,88,0,0,0,1,0
19,1,10020,2,2,0,0,0,3,3,121,...,99,17,18,99,99,0,0,0,1,0
20,1,10021,2,2,0,0,0,4,4,115,...,99,14,5,99,99,27,0,0,1,0
21,1,10022,1,1,0,0,0,2,2,127,...,99,6,30,99,99,0,0,0,1,0
22,1,10023,1,1,0,0,0,1,1,11,...,99,21,25,88,88,0,0,0,1,1
23,1,10024,1,1,0,0,0,1,1,5,...,99,6,25,99,99,0,0,0,1,0
24,1,10025,1,1,0,0,0,2,2,125,...,88,88,88,88,88,0,0,0,2,1
25,1,10026,1,1,0,0,0,1,1,73,...,99,13,42,88,88,0,0,0,1,0
26,1,10027,2,2,0,0,0,3,3,3,...,99,14,47,99,99,0,0,0,1,0
27,1,10028,1,1,0,0,0,1,1,1,...,99,0,40,88,88,0,0,0,1,1
28,1,10029,1,1,0,0,0,1,1,69,...,99,5,52,88,88,0,0,0,1,0
29,1,10030,2,2,0,0,0,5,5,21,...,99,13,35,88,88,0,0,0,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34409,56,560071,2,2,0,0,0,3,3,29,...,28,12,28,99,99,0,0,0,2,0
34410,56,560072,1,1,0,0,0,1,1,33,...,29,7,0,88,88,0,0,0,1,1
34411,56,560073,2,2,0,0,0,4,4,31,...,29,21,44,88,88,0,0,0,1,0
34412,56,560074,1,1,0,0,0,2,2,31,...,48,16,57,17,52,0,0,0,1,0
34413,56,560075,1,1,0,0,0,3,3,27,...,1,12,35,12,50,0,0,0,1,0
34414,56,560076,1,1,0,1,1,1,1,21,...,52,20,53,21,20,0,0,0,1,0
34415,56,560077,1,1,0,0,0,1,1,7,...,25,17,35,88,88,0,0,0,1,1
34416,56,560078,2,2,0,0,0,3,3,1,...,1,14,7,88,88,0,0,0,1,0
34417,56,560079,2,2,0,0,0,2,2,33,...,32,21,45,21,52,0,0,0,1,1
34418,56,560080,1,1,0,0,0,1,1,37,...,34,4,43,5,43,0,0,0,1,1
34419,56,560081,2,2,0,0,0,3,3,9,...,48,9,51,10,41,0,0,0,1,0
34420,56,560082,1,1,0,0,0,1,1,21,...,18,15,23,88,88,0,0,0,1,0
34421,56,560083,3,3,0,0,0,3,3,37,...,38,9,42,10,19,0,0,0,1,0
34422,56,560084,1,1,0,0,0,1,1,1,...,10,5,26,88,88,0,0,0,1,1
34423,56,560085,1,1,0,0,0,1,1,25,...,6,16,22,88,88,0,0,0,1,1
34424,56,560086,1,1,0,0,0,1,1,23,...,36,2,46,88,88,0,0,0,1,1
34425,56,560087,1,1,0,0,0,1,1,19,...,58,17,10,18,24,0,0,0,1,1
34426,56,560088,1,1,0,0,0,1,1,13,...,36,14,57,15,45,0,0,0,1,1
34427,56,560089,2,2,0,0,0,2,2,13,...,2,17,12,17,50,0,0,0,1,1
34428,56,560090,1,1,0,1,1,1,1,13,...,23,6,35,7,1,0,0,0,1,0
34429,56,560091,1,1,0,0,0,1,1,19,...,53,9,31,88,88,0,0,0,1,1
34430,56,560092,2,2,0,0,0,5,5,1,...,6,23,21,0,32,0,0,0,2,0
34431,56,560093,1,1,0,0,0,2,2,19,...,36,18,43,19,26,0,0,0,1,0
34432,56,560094,2,2,0,0,0,5,5,21,...,23,18,29,18,46,0,0,0,1,0
34433,56,560095,2,2,0,0,0,7,7,13,...,19,0,36,1,2,0,0,0,3,0
34434,56,560096,2,2,0,0,0,5,5,7,...,3,16,47,18,21,19,0,0,1,0
34435,56,560097,2,2,0,0,0,4,4,27,...,9,9,26,9,49,0,0,0,1,0
34436,56,560098,2,1,1,1,1,1,1,19,...,99,99,97,99,97,0,0,0,1,0
34437,56,560099,1,1,0,0,0,1,1,7,...,27,4,49,88,88,0,0,0,1,0
34438,56,560100,2,2,0,0,0,4,4,21,...,27,13,51,15,4,0,0,0,1,0

In [33]:
fars_df

,STATE,ST_CASE,VE_TOTAL,VE_FORMS,PVH_INVL,PEDS,PERNOTMVIT,PERMVIT,PERSONS,COUNTY,...,NOT_MIN,ARR_HOUR,ARR_MIN,HOSP_HR,HOSP_MN,CF1,CF2,CF3,FATALS,DRUNK_DR
0,1,10001,1,1,0,0,0,1,1,127,...,99,2,58,88,88,0,0,0,1,1
1,1,10002,1,1,0,0,0,1,1,83,...,99,22,20,88,88,0,0,0,1,0
2,1,10003,1,1,0,0,0,2,2,11,...,99,1,45,99,99,0,0,0,1,1
3,1,10004,1,1,0,0,0,1,1,45,...,99,1,15,88,88,0,0,0,1,1
4,1,10005,2,2,0,0,0,2,2,45,...,99,7,16,88,88,0,0,0,1,0
5,1,10006,1,1,0,0,0,2,2,111,...,99,10,17,99,99,0,0,0,1,0
6,1,10007,1,1,0,0,0,2,2,89,...,99,18,38,99,99,0,0,0,1,0
7,1,10008,1,1,0,1,1,1,1,73,...,99,21,48,99,99,0,0,0,1,0
8,1,10009,1,1,0,0,0,1,1,117,...,99,8,3,88,88,0,0,0,1,0
9,1,10010,2,2,0,0,0,2,2,33,...,99,19,1,99,99,0,0,0,1,0
10,1,10011,2,2,0,0,0,2,2,83,...,99,21,20,88,88,0,0,0,1,0
11,1,10012,3,3,0,0,0,6,6,95,...,99,6,41,99,99,0,0,0,1,0
12,1,10013,1,1,0,0,0,1,1,87,...,88,88,88,88,88,0,0,0,1,1
13,1,10014,1,1,0,0,0,1,1,11,...,99,6,29,88,88,0,0,0,1,1
14,1,10015,1,1,0,0,0,1,1,127,...,99,8,55,88,88,0,0,0,1,0
15,1,10016,2,2,0,0,0,2,2,81,...,99,17,30,99,99,0,0,0,1,0
16,1,10017,1,1,0,0,0,1,1,97,...,99,14,50,99,99,0,0,0,1,0
17,1,10018,1,1,0,0,0,2,2,1,...,99,19,35,99,99,0,0,0,1,1
18,1,10019,1,1,0,0,0,1,1,121,...,88,88,88,88,88,0,0,0,1,0
19,1,10020,2,2,0,0,0,3,3,121,...,99,17,18,99,99,0,0,0,1,0
20,1,10021,2,2,0,0,0,4,4,115,...,99,14,5,99,99,27,0,0,1,0
21,1,10022,1,1,0,0,0,2,2,127,...,99,6,30,99,99,0,0,0,1,0
22,1,10023,1,1,0,0,0,1,1,11,...,99,21,25,88,88,0,0,0,1,1
23,1,10024,1,1,0,0,0,1,1,5,...,99,6,25,99,99,0,0,0,1,0
24,1,10025,1,1,0,0,0,2,2,125,...,88,88,88,88,88,0,0,0,2,1
25,1,10026,1,1,0,0,0,1,1,73,...,99,13,42,88,88,0,0,0,1,0
26,1,10027,2,2,0,0,0,3,3,3,...,99,14,47,99,99,0,0,0,1,0
27,1,10028,1,1,0,0,0,1,1,1,...,99,0,40,88,88,0,0,0,1,1
28,1,10029,1,1,0,0,0,1,1,69,...,99,5,52,88,88,0,0,0,1,0
29,1,10030,2,2,0,0,0,5,5,21,...,99,13,35,88,88,0,0,0,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34409,56,560071,2,2,0,0,0,3,3,29,...,28,12,28,99,99,0,0,0,2,0
34410,56,560072,1,1,0,0,0,1,1,33,...,29,7,0,88,88,0,0,0,1,1
34411,56,560073,2,2,0,0,0,4,4,31,...,29,21,44,88,88,0,0,0,1,0
34412,56,560074,1,1,0,0,0,2,2,31,...,48,16,57,17,52,0,0,0,1,0
34413,56,560075,1,1,0,0,0,3,3,27,...,1,12,35,12,50,0,0,0,1,0
34414,56,560076,1,1,0,1,1,1,1,21,...,52,20,53,21,20,0,0,0,1,0
34415,56,560077,1,1,0,0,0,1,1,7,...,25,17,35,88,88,0,0,0,1,1
34416,56,560078,2,2,0,0,0,3,3,1,...,1,14,7,88,88,0,0,0,1,0
34417,56,560079,2,2,0,0,0,2,2,33,...,32,21,45,21,52,0,0,0,1,1
34418,56,560080,1,1,0,0,0,1,1,37,...,34,4,43,5,43,0,0,0,1,1
34419,56,560081,2,2,0,0,0,3,3,9,...,48,9,51,10,41,0,0,0,1,0
34420,56,560082,1,1,0,0,0,1,1,21,...,18,15,23,88,88,0,0,0,1,0
34421,56,560083,3,3,0,0,0,3,3,37,...,38,9,42,10,19,0,0,0,1,0
34422,56,560084,1,1,0,0,0,1,1,1,...,10,5,26,88,88,0,0,0,1,1
34423,56,560085,1,1,0,0,0,1,1,25,...,6,16,22,88,88,0,0,0,1,1
34424,56,560086,1,1,0,0,0,1,1,23,...,36,2,46,88,88,0,0,0,1,1
34425,56,560087,1,1,0,0,0,1,1,19,...,58,17,10,18,24,0,0,0,1,1
34426,56,560088,1,1,0,0,0,1,1,13,...,36,14,57,15,45,0,0,0,1,1
34427,56,560089,2,2,0,0,0,2,2,13,...,2,17,12,17,50,0,0,0,1,1
34428,56,560090,1,1,0,1,1,1,1,13,...,23,6,35,7,1,0,0,0,1,0
34429,56,560091,1,1,0,0,0,1,1,19,...,53,9,31,88,88,0,0,0,1,1
34430,56,560092,2,2,0,0,0,5,5,1,...,6,23,21,0,32,0,0,0,2,0
34431,56,560093,1,1,0,0,0,2,2,19,...,36,18,43,19,26,0,0,0,1,0
34432,56,560094,2,2,0,0,0,5,5,21,...,23,18,29,18,46,0,0,0,1,0
34433,56,560095,2,2,0,0,0,7,7,13,...,19,0,36,1,2,0,0,0,3,0
34434,56,560096,2,2,0,0,0,5,5,7,...,3,16,47,18,21,19,0,0,1,0
34435,56,560097,2,2,0,0,0,4,4,27,...,9,9,26,9,49,0,0,0,1,0
34436,56,560098,2,1,1,1,1,1,1,19,...,99,99,97,99,97,0,0,0,1,0
34437,56,560099,1,1,0,0,0,1,1,7,...,27,4,49,88,88,0,0,0,1,0
34438,56,560100,2,2,0,0,0,4,4,21,...,27,13,51,15,4,0,0,0,1,0

In [42]:
fars_df.shape

(66172, 52)

In [41]:
fars_df = fars_df[(fars_df['LONGITUD']<700)]

In [51]:
fars_spdf = arcgis.features.SpatialDataFrame.from_df(fars_df)

ValueError: Address column not found in dataframe

In [12]:
# Create a file geodatabase table
fgdb = arcpy.CreateFileGDB_management(workspace, "fars_full.gdb").getOutput(0)

In [13]:
# Copy csv to arcgis fgdb table
fars_gis_table = arcpy.TableToTable_conversion(fars_csv, fgdb, "fars_full").getOutput(0)

In [18]:
# Create XY Layer and save to disk
fars_xy_evtlyr = arcpy.MakeXYEventLayer_management(fars_gis_table, in_x_field="LONGITUD", in_y_field="LATITUDE").getOutput(0)
fars_fc = arcpy.CopyFeatures_management(fars_xy_evtlyr, os.path.join(fgdb, "fars_accidents")).getOutput(0)

In [19]:
fars_fc

'C:\\Users\\albe9057\\Documents\\GitHub\\FatalCarAccidents_SpatialAnalysis\\inputs\\fars_full.gdb\\fars_accidents'

In [36]:
def create_point_fc(input_table,
                    in_x_field,
                    in_y_field,
                    workspace_gdb,
                    point_fc_name,
                    spatial_reference=arcpy.SpatialReference('WGS 1984'),
                    table_format='csv'):
    """
    Converts an input table (csv or GIS) to a point feature class
    :param input_table:
    :param in_x_field:
    :param in_y_field:
    :param workspace_gdb:
    :param point_fc_name:
    :param spatial_reference:
    :param table_format: 'csv' or 'gis_table'
    :return:
    """
    # TODO - Add Warning and Error checking for spatial reference param
    output_point_fc = "{0}\{1}".format(workspace_gdb, point_fc_name)

    if table_format == 'csv':
        print("Converting csv to gis_table format...")
        gis_table_name = point_fc_name + "_temptable"
        if arcpy.Exists("{0}//{1}".format(workspace_gdb, gis_table_name)):
            print("\nExisting {0} GIS table exists. Replacing...".format(gis_table_name))
            try:
                arcpy.Delete_management("{0}//{1}".format(workspace_gdb, gis_table_name))
            except Exception as e:
                print(Exception)
        # Convert the csv to a GIS FGDB table
        input_table = arcpy.TableToTable_conversion(input_table, workspace_gdb, gis_table_name)

    print("Creating the point feature class...")
    if arcpy.Exists(input_table):
        # arcpy.env.overwriteOutput can have issues... therefore:
        if arcpy.Exists(output_point_fc):
            arcpy.Delete_management(output_point_fc)
        try:
            arcpy.MakeXYEventLayer_management(input_table, in_x_field, in_y_field, output_point_fc, spatial_reference)
            output_fc = arcpy.FeatureClassToFeatureClass_conversion(output_point_fc, workspace_gdb, point_fc_name).getOutput(0)
            print("point layer successfully created.\n")
            return output_fc
        except Exception:
            print(Exception)
            print("An error occurred while creating the point feature class. Please check the script log.\n")

    else:
        print("The " + input_table + " table does not exist in the geodatabase. The point feature class could not be created.\n")

In [38]:
fars_fc = create_point_fc(fars_csv, "LONGITUD", "LATITUDE", fgdb, "fars_accidents_2015_2016", arcpy.SpatialReference(4326))

Converting csv to gis_table format...

Existing fars_accidents_2015_2016_temptable GIS table exists. Replacing...
Creating the point feature class...
point layer successfully created.

In [24]:
fars_fc

'C:\\Users\\albe9057\\Documents\\GitHub\\FatalCarAccidents_SpatialAnalysis\\inputs\\fars_full.gdb\\fars_accidents_2015_2016'

### 3. Analyze and model: Break the problem down into solvable components that can be modeled. Quantify and evaluate the spatial questions.

##### Processing of Cluster Prioritization

Logic:

1. Produce DBSCAN specified-distance Clusters (300m and 3 features per cluster)
2. Filter by clusters where all members have the same HARM_EV value
3. Filter by clusters where all members have the same TWAY_ID | TWAY_ID2 | ROUTE | FUNC_SYS value
4. For each HARM_EV category, calculate Priority score using amount of events and amount of traffic

##### Supplemental Notes (Approach not fully used)

Priority Score
* Amount of events
* Uniformity of events ("uniformity score")
* Amount of Traffic (Population Counts if traffic not quickly accessible - flawed but better than nothing on a short turnaround.)

Fields for uniformity score:
* First Harmful Event Groupings (HARM_EV)
    * HARM_EV 12 = Motor Vehicle in Transport (13051)
    * HARM_EV 8 = Pedestrian (5488)
    * HARM_EV 1 = Rollover/Overturn (3049)
    * HARM_EV 42 = Tree (2522)
    * HARM_EV 33 = Curb (1065)
    * HARM_EV 34 = Ditch (958)
    * HARM_EV 35 = Embankment (942)
    * HARM_EV 9 = Pedalcyclist (809)
    * HARM_EV 24 = Guardrail Face (710)
    * HARM_EV 30 = Utility Pole/Light Support (686)
    * HARM_EV 32 = Culvert (475)
    * HARM_EV 38 = Fence (438)
    
    Others...
    * HARM_EV 10 = Train
    * HARM_EV 11 = Animal
    * HARM_EV 19 = Boulder
    * HARM_EV 21 = Bridge Pier
    * HARM_EV 72 = Cargo/Equipment Loss or Shift (Harmful to This Vehicle)
    * HARM_EV 73 = Object Fell From Motor Vehicle In-Transport
    * HARM_EV 59 = Traffic Sign Support
    
* DRUNK_DR
* FATALS
* PEDS
* PERNOTMVIT (Number of Persons Not in Motor Vehicles in Transport (MVIT))
* PVH_INVL (Number of Parked/Working Vehicles)
* TWAY_ID / TWAY_ID2 + ROUTE + FUNC_SYS = Same Road Segment?

In [10]:
# Set reference to the output cluster feature class
clusters_fc = r"C:\Users\albe9057\Documents\ANieto_SolutionEngineering\Projects\SpatialStats\ML_ProblemCases\Clustering\Work\Clustering_Project\Clustering_Project.gdb\FARS_Clusters_300m_3min_app"

In [16]:
field_list = [field.name for field in arcpy.ListFields(clusters_fc)]
field_list

['OBJECTID',
 'Shape',
 'FARS_Clusters_300m_3min_SOURCE_ID',
 'FARS_Clusters_300m_3min_CLUSTER_ID',
 'FARS_Clusters_300m_3min_COLOR_ID',
 'fars_accidents_2015_BTS_OBJECTID',
 'fars_accidents_2015_BTS_STATE',
 'fars_accidents_2015_BTS_ST_CASE',
 'fars_accidents_2015_BTS_VE_TOTAL',
 'fars_accidents_2015_BTS_VE_FORMS',
 'fars_accidents_2015_BTS_PVH_INVL',
 'fars_accidents_2015_BTS_PEDS',
 'fars_accidents_2015_BTS_PERNOTMVIT',
 'fars_accidents_2015_BTS_PERMVIT',
 'fars_accidents_2015_BTS_PERSONS',
 'fars_accidents_2015_BTS_COUNTY',
 'fars_accidents_2015_BTS_CITY',
 'fars_accidents_2015_BTS_DAY_',
 'fars_accidents_2015_BTS_MONTH_',
 'fars_accidents_2015_BTS_YEAR_',
 'fars_accidents_2015_BTS_DAY_WEEK',
 'fars_accidents_2015_BTS_HOUR_',
 'fars_accidents_2015_BTS_MINUTE_',
 'fars_accidents_2015_BTS_NHS',
 'fars_accidents_2015_BTS_RUR_URB',
 'fars_accidents_2015_BTS_FUNC_SYS',
 'fars_accidents_2015_BTS_RD_OWNER',
 'fars_accidents_2015_BTS_ROUTE',
 'fars_accidents_2015_BTS_TWAY_ID',
 'fars_accidents_2015_BTS_TWAY_ID2',
 'fars_accidents_2015_BTS_MILEPT',
 'fars_accidents_2015_BTS_LATITUDE',
 'fars_accidents_2015_BTS_LONGITUD',
 'fars_accidents_2015_BTS_SP_JUR',
 'fars_accidents_2015_BTS_HARM_EV',
 'fars_accidents_2015_BTS_MAN_COLL',
 'fars_accidents_2015_BTS_RELJCT1',
 'fars_accidents_2015_BTS_RELJCT2',
 'fars_accidents_2015_BTS_TYP_INT',
 'fars_accidents_2015_BTS_WRK_ZONE',
 'fars_accidents_2015_BTS_REL_ROAD',
 'fars_accidents_2015_BTS_LGT_COND',
 'fars_accidents_2015_BTS_WEATHER1',
 'fars_accidents_2015_BTS_WEATHER2',
 'fars_accidents_2015_BTS_WEATHER',
 'fars_accidents_2015_BTS_SCH_BUS',
 'fars_accidents_2015_BTS_RAIL',
 'fars_accidents_2015_BTS_NOT_HOUR',
 'fars_accidents_2015_BTS_NOT_MIN',
 'fars_accidents_2015_BTS_ARR_HOUR',
 'fars_accidents_2015_BTS_ARR_MIN',
 'fars_accidents_2015_BTS_HOSP_HR',
 'fars_accidents_2015_BTS_HOSP_MN',
 'fars_accidents_2015_BTS_CF1',
 'fars_accidents_2015_BTS_CF2',
 'fars_accidents_2015_BTS_CF3',
 'fars_accidents_2015_BTS_FATALS',
 'fars_accidents_2015_BTS_DRUNK_DR',
 'COUNT',
 'HARM_EV_CATEGORICAL']

In [11]:
# Helper function
def convert_featureclass_to_pddataframe(fc, fields_list=["*"], remove_index=False):
    """
    Converts a feature class to a pandas dataframe.
    :param fc: Input feature class
    :param fields_list: Optional parameter - defaults to wildcard ["*"]. Optionally include specific fields.
    :param remove_index: Optional parameter - defaults to False. Remove index from output dataframe.
    :return: Pandas dataframe of the feature class WITHOUT geometry and date attributes.
    """
    # Gather a list of all field names if the user did not specify field inputs
    if fields_list == ["*"]:
        # Generate a valid list of field names that can be passed to the arcpy.FeatureClassToNumPyArray function
        # (must filter out geometry and date fields!
        fields_list = [field_object.name for field_object in arcpy.ListFields(fc) if field_object.type not in ["Geometry", "Date"]]

    temp_array = arcpy.da.FeatureClassToNumPyArray(fc, fields_list)
    df = pd.DataFrame(data=temp_array)
    if remove_index:
        df.reset_index(inplace=True)
    return df

In [ ]:
# Export to a pandas dataframe for quick filtering operations (could be done manually in ArcGIS)
clusters_df = convert_featureclass_to_pddataframe(clusters_fc, fields_list = field_list)
clusters_df

In [19]:
clusters_csv = r"C:\Users\albe9057\Documents\GitHub\FatalCarAccidents_SpatialAnalysis\inputs\FARS_Clusters_300m_3min.csv"
clusters_df = pd.read_csv(clusters_csv)
clusters_df

,OBJECTID,FARS_Clusters_300m_3min_SOURCE_ID,FARS_Clusters_300m_3min_CLUSTER_ID,FARS_Clusters_300m_3min_COLOR_ID,fars_accidents_2015_BTS_OBJECTID,fars_accidents_2015_BTS_STATE,fars_accidents_2015_BTS_ST_CASE,fars_accidents_2015_BTS_VE_TOTAL,fars_accidents_2015_BTS_VE_FORMS,fars_accidents_2015_BTS_PVH_INVL,...,fars_accidents_2015_BTS_ARR_MIN,fars_accidents_2015_BTS_HOSP_HR,fars_accidents_2015_BTS_HOSP_MN,fars_accidents_2015_BTS_CF1,fars_accidents_2015_BTS_CF2,fars_accidents_2015_BTS_CF3,fars_accidents_2015_BTS_FATALS,fars_accidents_2015_BTS_DRUNK_DR,COUNT,HARM_EV_CATEGORICAL
0,1,1,-1,-1,1,1,10001,1,1,0,...,36,88,88,0,0,0,1,1,1,42
1,2,2,-1,-1,2,1,10002,1,1,0,...,5,99,99,0,0,0,1,1,1,1
2,3,3,-1,-1,3,1,10003,2,1,1,...,31,88,88,0,0,0,1,0,1,14
3,4,4,-1,-1,4,1,10004,1,1,0,...,57,99,99,0,0,0,1,1,1,25
4,5,5,-1,-1,5,1,10005,1,1,0,...,10,88,88,0,0,0,1,0,1,42
5,6,6,-1,-1,6,1,10006,1,1,0,...,31,88,88,0,0,0,1,0,1,42
6,7,7,-1,-1,7,1,10007,1,1,0,...,39,88,88,0,0,0,1,0,1,42
7,8,8,-1,-1,8,1,10008,1,1,0,...,50,88,88,0,0,0,1,1,1,32
8,9,9,-1,-1,9,1,10009,2,2,0,...,50,99,99,0,0,0,2,0,1,12
9,10,10,-1,-1,10,1,10010,1,1,0,...,30,88,88,0,0,0,2,1,1,1
10,11,11,-1,-1,11,1,10011,2,2,0,...,12,88,88,0,0,0,1,0,1,12
11,12,12,-1,-1,12,1,10012,1,1,0,...,26,99,99,0,0,0,1,0,1,42
12,13,13,-1,-1,13,1,10013,1,1,0,...,26,18,4,15,0,0,1,0,1,8
13,14,14,-1,-1,14,1,10014,2,2,0,...,41,99,99,0,0,0,1,1,1,12
14,15,15,-1,-1,15,1,10015,2,2,0,...,36,99,99,0,0,0,1,1,1,12
15,16,16,-1,-1,16,1,10016,1,1,0,...,88,88,88,0,0,0,1,0,1,42
16,17,17,-1,-1,17,1,10017,1,1,0,...,54,88,88,0,0,0,1,1,1,34
17,18,18,-1,-1,18,1,10018,1,1,0,...,15,88,88,0,0,0,1,0,1,34
18,19,19,-1,-1,19,1,10019,1,1,0,...,46,17,9,0,0,0,1,0,1,34
19,20,20,-1,-1,20,1,10020,3,2,1,...,43,2,12,0,0,0,4,1,1,12
20,21,21,-1,-1,21,1,10021,2,2,0,...,44,8,0,0,0,0,1,0,1,12
21,22,22,-1,-1,22,1,10022,4,2,2,...,46,11,5,20,14,0,1,0,1,12
22,23,23,-1,-1,23,1,10023,1,1,0,...,55,88,88,0,0,0,2,0,1,34
23,24,24,-1,-1,24,1,10024,2,1,1,...,59,99,99,14,0,0,1,0,1,8
24,25,25,-1,-1,25,1,10025,2,2,0,...,2,99,99,0,0,0,1,1,1,12
25,26,26,-1,-1,26,1,10026,3,3,0,...,57,99,99,0,0,0,1,0,1,1
26,27,27,-1,-1,27,1,10027,1,1,0,...,20,88,88,0,0,0,1,1,1,42
27,28,28,-1,-1,28,1,10028,1,1,0,...,47,99,99,0,0,0,2,0,1,42
28,29,29,-1,-1,29,1,10029,2,2,0,...,41,99,99,0,0,0,1,0,1,12
29,30,30,-1,-1,30,1,10030,1,1,0,...,28,99,99,0,0,0,1,0,1,42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34183,34184,34410,-1,-1,34410,56,560071,2,2,0,...,28,99,99,0,0,0,2,0,1,12
34184,34185,34411,-1,-1,34411,56,560072,1,1,0,...,0,88,88,0,0,0,1,1,1,1
34185,34186,34412,-1,-1,34412,56,560073,2,2,0,...,44,88,88,0,0,0,1,0,1,18
34186,34187,34413,-1,-1,34413,56,560074,1,1,0,...,57,17,52,0,0,0,1,0,1,31
34187,34188,34414,-1,-1,34414,56,560075,1,1,0,...,35,12,50,0,0,0,1,0,1,1
34188,34189,34415,-1,-1,34415,56,560076,1,1,0,...,53,21,20,0,0,0,1,0,1,8
34189,34190,34416,-1,-1,34416,56,560077,1,1,0,...,35,88,88,0,0,0,1,1,1,1
34190,34191,34417,-1,-1,34417,56,560078,2,2,0,...,7,88,88,0,0,0,1,0,1,12
34191,34192,34418,-1,-1,34418,56,560079,2,2,0,...,45,21,52,0,0,0,1,1,1,12
34192,34193,34419,-1,-1,34419,56,560080,1,1,0,...,43,5,43,0,0,0,1,1,1,34
34193,34194,34420,-1,-1,34420,56,560081,2,2,0,...,51,10,41,0,0,0,1,0,1,12
34194,34195,34421,-1,-1,34421,56,560082,1,1,0,...,23,88,88,0,0,0,1,0,1,38
34195,34196,34422,-1,-1,34422,56,560083,3,3,0,...,42,10,19,0,0,0,1,0,1,12
34196,34197,34423,-1,-1,34423,56,560084,1,1,0,...,26,88,88,0,0,0,1,1,1,1
34197,34198,34424,-1,-1,34424,56,560085,1,1,0,...,22,88,88,0,0,0,1,1,1,1
34198,34199,34425,-1,-1,34425,56,560086,1,1,0,...,46,88,88,0,0,0,1,1,1,1
34199,34200,34426,-1,-1,34426,56,560087,1,1,0,...,10,18,24,0,0,0,1,1,1,31
34200,34201,34427,-1,-1,34427,56,560088,1,1,0,...,57,15,45,0,0,0,1,1,1,1
34201,34202,34428,-1,-1,34428,56,560089,2,2,0,...,12,17,50,0,0,0,1,1,1,12
34202,34203,34429,-1,-1,34429,56,560090,1,1,0,...,35,7,1,0,0,0,1,0,1,8
34203,34204,34430,-1,-1,34430,56,560091,1,1,0,...,31,88,88,0,0,0,1,1,1,1
34204,34205,34431,-1,-1,34431,56,560092,2,2,0,...,21,0,32,0,0,0,2,0,1,12
34205,34206,34432,-1,-1,34432,56,560093,1,1,0,...,43,19,26,0,0,0,1,0,1,1
34206,34207,34433,-1,-1,34433,56,560094,2,2,0,...,29,18,46,0,0,0,1,0,1,12
34207,34208,34434,-1,-1,34434,56,560095,2,2,0,...,36,1,2,0,0,0,3,0,1,12
34208,34209,34435,-1,-1,34435,56,560096,2,2,0,...,47,18,21,19,0,0,1,0,1,12
34209,34210,34436,-1,-1,34436,56,560097,2,2,0,...,26,9,49,0,0,0,1,0,1,12
34210,34211,34437,-1,-1,34437,56,560098,2,1,1,...,97,99,97,0,0,0,1,0,1,14
34211,34212,34438,-1,-1,34438,56,560099,1,1,0,...,49,88,88,0,0,0,1,0,1,1
34212,34213,34439,-1,-1,34439,56,560100,2,2,0,...,51,15,4,0,0,0,1,0,1,12

We need a table of cluster IDs where each cluster has the same HARM_EV value!

In [20]:
clusters_df.columns

Index(['OBJECTID', 'FARS_Clusters_300m_3min_SOURCE_ID',
       'FARS_Clusters_300m_3min_CLUSTER_ID',
       'FARS_Clusters_300m_3min_COLOR_ID', 'fars_accidents_2015_BTS_OBJECTID',
       'fars_accidents_2015_BTS_STATE', 'fars_accidents_2015_BTS_ST_CASE',
       'fars_accidents_2015_BTS_VE_TOTAL', 'fars_accidents_2015_BTS_VE_FORMS',
       'fars_accidents_2015_BTS_PVH_INVL', 'fars_accidents_2015_BTS_PEDS',
       'fars_accidents_2015_BTS_PERNOTMVIT', 'fars_accidents_2015_BTS_PERMVIT',
       'fars_accidents_2015_BTS_PERSONS', 'fars_accidents_2015_BTS_COUNTY',
       'fars_accidents_2015_BTS_CITY', 'fars_accidents_2015_BTS_DAY_',
       'fars_accidents_2015_BTS_MONTH_', 'fars_accidents_2015_BTS_YEAR_',
       'fars_accidents_2015_BTS_DAY_WEEK', 'fars_accidents_2015_BTS_HOUR_',
       'fars_accidents_2015_BTS_MINUTE_', 'fars_accidents_2015_BTS_NHS',
       'fars_accidents_2015_BTS_RUR_URB', 'fars_accidents_2015_BTS_FUNC_SYS',
       'fars_accidents_2015_BTS_RD_OWNER', 'fars_accidents_2015_BTS_ROUTE',
       'fars_accidents_2015_BTS_TWAY_ID', 'fars_accidents_2015_BTS_TWAY_ID2',
       'fars_accidents_2015_BTS_MILEPT', 'fars_accidents_2015_BTS_LATITUDE',
       'fars_accidents_2015_BTS_LONGITUD', 'fars_accidents_2015_BTS_SP_JUR',
       'fars_accidents_2015_BTS_HARM_EV', 'fars_accidents_2015_BTS_MAN_COLL',
       'fars_accidents_2015_BTS_RELJCT1', 'fars_accidents_2015_BTS_RELJCT2',
       'fars_accidents_2015_BTS_TYP_INT', 'fars_accidents_2015_BTS_WRK_ZONE',
       'fars_accidents_2015_BTS_REL_ROAD', 'fars_accidents_2015_BTS_LGT_COND',
       'fars_accidents_2015_BTS_WEATHER1', 'fars_accidents_2015_BTS_WEATHER2',
       'fars_accidents_2015_BTS_WEATHER', 'fars_accidents_2015_BTS_SCH_BUS',
       'fars_accidents_2015_BTS_RAIL', 'fars_accidents_2015_BTS_NOT_HOUR',
       'fars_accidents_2015_BTS_NOT_MIN', 'fars_accidents_2015_BTS_ARR_HOUR',
       'fars_accidents_2015_BTS_ARR_MIN', 'fars_accidents_2015_BTS_HOSP_HR',
       'fars_accidents_2015_BTS_HOSP_MN', 'fars_accidents_2015_BTS_CF1',
       'fars_accidents_2015_BTS_CF2', 'fars_accidents_2015_BTS_CF3',
       'fars_accidents_2015_BTS_FATALS', 'fars_accidents_2015_BTS_DRUNK_DR',
       'COUNT', 'HARM_EV_CATEGORICAL'],
      dtype='object')

In [89]:
# Group by cluster ID and by the HARM_EV value
cluster_grpby = clusters_df.groupby(['FARS_Clusters_300m_3min_CLUSTER_ID', 'HARM_EV_CATEGORICAL'])
cluster_grpby.sum()

                                                         OBJECTID  \
FARS_Clusters_300m_3min_CLUSTER_ID HARM_EV_CATEGORICAL
-1                                 1                     53279074
                                   2                        40755
                                   3                       993595
                                   5                      3712145
                                   6                        36468
                                   7                       763678
                                   8                     88960382
                                   9                     12032658
                                   10                     1658360
                                   11                     3628977
                                   12                   222658157
                                   14                     6516828
                                   15                     2435871
                                   16                      329611
                                   17                     1349517
                                   18                     2793119
                                   19                     1108929
                                   20                      728247
                                   21                     2224781
                                   23                     1970254
                                   24                    12842821
                                   25                     5664807
                                   26                      926867
                                   30                    12110080
                                   31                     4325777
                                   32                     8201556
                                   33                    15329367
                                   34                    17716192
                                   35                    16858618
                                   38                     7408680
...                                                           ...
 51                                12                       24709
 52                                1                        25572
                                   8                        25566
                                   12                       25869
 53                                8                       104222
 54                                8                        26932
                                   12                       53209
 55                                8                        27719
                                   12                       55333
 56                                12                       55522
                                   59                       27780
 57                                9                        28596
                                   12                       28551
                                   26                       30928
 58                                8                        58475
                                   12                       30319
 59                                12                       60019
                                   30                       29102
                                   33                       29696
 60                                12                       89596
 61                                8                        28812
                                   30                       28843
                                   33                       29261
 62                                12                       89821
 63                                12                       91689
 64                                12                       30922
                                   23                       30945
                                   24                       29039
 65                                8                        31164
                                   12                       62223

                                                        FARS_Clusters_300m_3min_SOURCE_ID  \
FARS_Clusters_300m_3min_CLUSTER_ID HARM_EV_CATEGORICAL
-1                                 1                                             53753910
                                   2                                                41307
                                   3                                              1003078
                                   5                                              3745624
                                   6                                                36941
                                   7                                               770352
                                   8                                             89791935
                                   9                                             12151275
                                   10                                             1673510
                                   11                                             3659819
                                   12                                           224696582
                                   14                                             6576902
                                   15                                             2459852
                                   16                                              332562
                                   17                                             1361852
                                   18                                             2818092
                                   19                                             1118595
                                   20                                              734976
                                   21                                             2244273
                                   23                                             1987475
                                   24                                            12958515
                                   25                                             5715775
                                   26                                              934911
                                   30                                            12219534
                                   31                                             4365557
                                   32                                             8275159
                                   33                                            15481307
                                   34                                            17872794
                                   35                                            17009162
                                   38                                             7475592
...                                                                                   ...
 51                                12                                               24928
 52                                1                                                25793
                                   8                                                25787
                                   12                                               26090
 53                                8                                               105106
 54                                8                                                27153
                                   12                                               53651
 55                                8                                                27942
                                   12                                               55779
 56                                12                                               55968
                                   59                                               28003
 57                                9                                                28819
                                   12                                               28774
                                   26                                               31151
 58                                8                                                58921
                                   12                                               30542
 59                                12                                               60465
                                   30                                               29325
                                   33                                               29919
 60                                12                                               90265
 61                                8                                                29035
                                   30                                               29066
                                   33                                               29484
 62                                12                                               90490
 63                                12                                               92358
 64                                12                                               31145
                                   23                                               31168
                                   24                                               29262
 65                                8                                                31387
                                   12                                               62669

                                                        FARS_Clusters_300m_3min_COLOR_ID  \
FARS_Clusters_300m_3min_CLUSTER_ID HARM_EV_CATEGORICAL
-1                                 1                                               -3038
                                   2                                                  -5
                                   3                                                 -63
                                   5                                                -218
                                   6                                                  -4
                                   7                                                 -37
                                   8                                               -5430
                                   9                                                -805
                                   10                                               -101
                                   11                                               -180
                                   12                                             -12965
                                   14                                               -386
                                   15                                               -160
                                   16                                                -19
                                   17                                                -87
                                   18                                               -157
                                   19                                                -57
                                   20                                                -43
                                   21                                               -117
                                   23                                               -107
                                   24                                               -705
                                   25                                               -312
                                   26                                                -45
                                   30                                               -681
                                   31                                               -248
                                   32                                               -475
                                   33                                              -1061
                                   34                                               -958
                                   35                                               -941
                                   38                                               -433
...                                                                                  ...
 51                                12                                                  3
 52                                1                                                   8
                                   8                                                   8
                                   12                                                  8
 53                                8                                                   8
 54                                8                                                   5
                                   12                                                 10
 55                                8                                                   5
                                   12                                                 10
 56                                12                                                  2
                                   59                                                  1
 57                                9                                                   4
                                   12                                                  4
                                   26                                                  4
 58                                8                                                   4
                                   12                                                  2
 59                                12                                                 10
                                   30                                                  5
                                   33                                                  5
 60                                12                                                 12
 61                                8                                                   6
                                   30                                                  6
                                   33                                                  6
 62                                12                                                  3
 63                                12                                                 21
 64                                12                                                  8
                                   23                                                  8
                                   24                                                  8
 65                                8                                                   1
                                   12                                                  2

                                                        fars_accidents_2015_BTS_OBJECTID  \
FARS_Clusters_300m_3min_CLUSTER_ID HARM_EV_CATEGORICAL
-1                                 1                                            53753910
                                   2                                               41307
                                   3                                             1003078
                                   5                                             3745624
                                   6                                               36941
                                   7                                              770352
                                   8                                            89791935
                                   9                                            12151275
                                   10                                            1673510
                                   11                                            3659819
                                   12                                          224696582
                                   14                                            6576902
                                   15                                            2459852
                                   16                                             332562
                                   17                                            1361852
                                   18                                            2818092
                                   19                                            1118595
                                   20                                             734976
                                   21                                            2244273
                                   23                                            1987475
                                   24                                           12958515
                                   25                                            5715775
                                   26                                             934911
                                   30                                           12219534
                                   31                                            4365557
                                   32                                            8275159
                                   33                                           15481307
                                   34                                           17872794
                                   35                                           17009162
                                   38                                            7475592
...                                                                                  ...
 51                                12                                              24928
 52                                1                                               25793
                                   8                                               25787
                                   12                                              26090
 53                                8                                              105106
 54                                8                                               27153
                                   12                                              53651
 55                                8                                               27942
                                   12                                              55779
 56                                12                                              55968
                                   59                                              28003
 57                                9                                               28819
                                   12                                              28774
                                   26                                              31151
 58                                8                                               58921
                                   12                                              30542
 59                                12                                              60465
                                   30                                              29325
                                   33                                              29919

In [97]:
# Get the mode of each HARM EV value for each cluster
clusters_df.groupby(['FARS_Clusters_300m_3min_CLUSTER_ID'])['HARM_EV_CATEGORICAL'].agg(pd.Series.mode)

FARS_Clusters_300m_3min_CLUSTER_ID
-1                      12
 1              [5, 8, 12]
 2            [12, 25, 26]
 3             [8, 12, 15]
 4                      12
 5            [12, 24, 58]
 6                 [8, 12]
 7              [1, 9, 42]
 8             [8, 12, 23]
 9                       8
 10                      8
 11                      8
 12                     33
 13                     12
 14            [8, 12, 25]
 15                     12
 16                     12
 17                     12
 18        [8, 12, 25, 30]
 19                     12
 20         [1, 8, 12, 25]
 21                      8
 22                      8
 23            [8, 12, 38]
 24                      8
 25                      8
 26                     52
 27           [12, 19, 25]
 28                     12
 29            [8, 12, 14]
              ...
 36                     12
 37                      8
 38           [12, 38, 42]
 39                      1
 40                     12
 41    [8, 12, 30, 38, 43]
 42                     12
 43                     42
 44                     12
 45                     12
 46                     12
 47             [1, 8, 12]
 48           [12, 42, 43]
 49             [3, 8, 12]
 50           [12, 35, 42]
 51                      8
 52             [1, 8, 12]
 53                      8
 54                     12
 55                     12
 56                     12
 57            [9, 12, 26]
 58                      8
 59                     12
 60                     12
 61            [8, 30, 33]
 62                     12
 63                     12
 64           [12, 23, 24]
 65                     12
Name: HARM_EV_CATEGORICAL, Length: 66, dtype: object

In [47]:
cluster_grpby = clusters_df.groupby('FARS_Clusters_300m_3min_CLUSTER_ID')
clusters_by_harm_ev = cluster_grpby.fars_accidents_2015_BTS_HARM_EV.unique().to_frame()
clusters_by_harm_ev

                                                      fars_accidents_2015_BTS_HARM_EV
FARS_Clusters_300m_3min_CLUSTER_ID
-1                                  [42, 1, 14, 25, 32, 12, 8, 34, 35, 53, 9, 30, ...
 1                                                                         [8, 5, 12]
 2                                                                       [26, 12, 25]
 3                                                                        [15, 12, 8]
 4                                                                            [12, 8]
 5                                                                       [12, 58, 24]
 6                                                                            [12, 8]
 7                                                                         [1, 9, 42]
 8                                                                        [12, 23, 8]
 9                                                                        [8, 20, 12]
 10                                                                            [8, 9]
 11                                                                           [8, 12]
 12                                                                       [33, 12, 1]
 13                                                                           [12, 8]
 14                                                                       [12, 25, 8]
 15                                                                           [12, 8]
 16                                                                          [12, 59]
 17                                                                          [24, 12]
 18                                                                   [12, 25, 8, 30]
 19                                                                        [12, 8, 9]
 20                                                                    [8, 12, 1, 25]
 21                                                                           [8, 12]
 22                                                                           [12, 8]
 23                                                                       [38, 8, 12]
 24                                                                               [8]
 25                                                                           [39, 8]
 26                                                                          [12, 52]
 27                                                                      [25, 19, 12]
 28                                                                      [30, 42, 12]
 29                                                                       [8, 14, 12]
...                                                                               ...
 36                                                                              [12]
 37                                                                            [8, 1]
 38                                                                      [42, 12, 38]
 39                                                                        [1, 8, 42]
 40                                                                          [12, 42]
 41                                                               [12, 8, 43, 38, 30]
 42                                                               [12, 59, 42, 8, 26]
 43                                                                          [12, 42]
 44                                                                       [12, 42, 8]
 45                                                                           [12, 1]
 46                                                                           [12, 8]
 47                                                                        [8, 1, 12]
 48                                                                      [12, 43, 42]
 49                                                                        [3, 12, 8]
 50                                                                      [12, 42, 35]
 51                                                                           [8, 12]
 52                                                                        [8, 1, 12]
 53                                                                               [8]
 54                                                                           [12, 8]
 55                                                                           [12, 8]
 56                                                                          [12, 59]
 57                                                                       [12, 9, 26]
 58                                                                           [8, 12]
 59                                                                      [12, 30, 33]
 60                                                                              [12]
 61                                                                       [8, 30, 33]
 62                                                                              [12]
 63                                                                              [12]
 64                                                                      [24, 12, 23]
 65                                                                           [12, 8]

[66 rows x 1 columns]

In [65]:
# Find Cluster IDs with only one type of HARM_EV 
for index, row in clusters_by_harm_ev.iterrows():
    if len(row['fars_accidents_2015_BTS_HARM_EV']) == 1:
        print(index, row['fars_accidents_2015_BTS_HARM_EV'])

24 [8]
33 [8]
36 [12]
53 [8]
60 [12]
62 [12]
63 [12]

In [66]:
# Find Cluster IDs with two types of HARM_EV 
for index, row in clusters_by_harm_ev.iterrows():
    if len(row['fars_accidents_2015_BTS_HARM_EV']) == 2:
        print(index, row['fars_accidents_2015_BTS_HARM_EV'])

4 [12  8]
6 [12  8]
10 [8 9]
11 [ 8 12]
13 [12  8]
15 [12  8]
16 [12 59]
17 [24 12]
21 [ 8 12]
22 [12  8]
25 [39  8]
26 [12 52]
30 [12  8]
37 [8 1]
40 [12 42]
43 [12 42]
45 [12  1]
46 [12  8]
51 [ 8 12]
54 [12  8]
55 [12  8]
56 [12 59]
58 [ 8 12]
65 [12  8]

In [ ]:
# For each cluster, calculate the following two fields:
# "MCHE: Most Common HARM_EV"
# "MCHE Percent of Incidents"

for cluster_id, row in clusters_by_harm_ev.iterrows():

In [ ]:
def calc_harmev_mode_and_freqpercent(clusters_fc, clusters_fc_id_field, clusters_fc_mode_field, clusters_fc_mfpfield, events_fc, events_fc_id_field, events_fc_harm_ev_field):
    with arcpy.da.UpdateCursor(clusters_fc, [clusters_fc_id_field, clusters_fc_mode_field, clusters_fc_mfpfield]) as cursor:
        for row in cursor:
            print("Processing cluster ID {0}...".format(str(row[0])))
            where_clause = arcpy.AddFieldDelimiters(events_fc, events_fc_id_field) + " = '" + str(row[0]) + "'"
            with arcpy.da.InsertCursor(events_fc, [events_fc_id_field, events_fc_harm_ev_field], where_clause) as evtcursor:
                mode = None

### 4. Interpret the results: Evaluate and analyze the results in the context of the question posed, data limitations, accuracy, and other implications.

### 5. Repeat as necessary: Spatial analysis is a continuous and iterative process that often leads to further questions and refinements.

### 6. Present the results: The best information and analysis becomes increasingly valuable when it can be effectively presented and shared with a larger audience.

### 7. Make a decision: Spatial analysis and GIS are used to support the decision-making process. A successful spatial analysis process often leads to the understanding necessary to drive decisions and action.

#### Pseudocode

1. Retrieve FARS data for five years.

2. Compile FARS data into single dataset using Pandas.

3. Convert to GIS format.

4. Append road features to each record.

5. Run Density-based Clustering